FROM python:3.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn pydantic jose passlib[bcrypt] typing datetime passlib 

EXPOSE 8000

CMD ["uvicorn", "registration_sys:app", "--host", "0.0.0.0", "--port", "8000"]